export const SIMPLE_EMAIL_REGEX = /^\S+@\S+\.\S+$/;
export const COMPLEX_EMAIL_REGEX = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|.(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
export const UUID_V4_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
export const UPPERCASE_LETTERS_REGEX = /[A-Z]/g;
export const LOWERCASE_LETTERS_REGEX = /[a-z]/g;
export const DIGITS_REGEX = /[0-9]/g;
export const SPECIAL_CHARS_REGEX = /[!@#$%^&*()\-\_=+\[\]{}|;:'",.<>?\/`~]/g;
export const CONSECUTIVE_CHARS_REGEX = /(.)\1+/gi;
export const HEX_COLOR_REGEX = /^#(?:[0-9a-f]{3}|[0-9a-f]{4}|[0-9a-f]{6}|[0-9a-f]{8})$/i;
export const MIME_TYPE_REGEX = /^[a-z0-9!#$&^_.+-]+\/[a-z0-9!#$&^_.+-]+(?:;[ \t]*[a-z0-9!#$&^_.+-]+=[a-z0-9!#$&^_.+-]+)*$/i;
export const SLUG_REGEX = /^[0-9a-z]+(?:-[0-9a-z]+)*$/;
export const FILE_REGEX = /\.[a-z]+$/i;

export const COMMON_PASSWORDS = [
  '123456', '123456789', '12345678', 'password',
  'qwerty123', 'qwerty1', '111111', '12345', 'secret',
  '123123', '1234567890', '1234567', '000000', 'qwerty',
  'abc123', 'password1', 'iloveyou', '11111111', 'dragon',
  'monkey',
];

export const MIME_TYPES = new Set<string>([
  "text/plain",
  "text/html",
  "text/css",
  "text/javascript",
  "text/csv",
  "text/xml",
  "text/markdown",
  "text/yaml",
  "text/cache-manifest",
  "text/calendar",
  "text/x-vcard",
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/webp",
  "image/avif",
  "image/svg+xml",
  "image/bmp",
  "image/tiff",
  "image/x-icon",
  "image/heic",
  "image/heif",
  "image/x-xbitmap",
  "image/vnd.microsoft.icon",
  "audio/mpeg",
  "audio/wav",
  "audio/ogg",
  "audio/webm",
  "audio/flac",
  "audio/aac",
  "audio/mp4",
  "audio/3gpp",
  "audio/amr",
  "audio/x-midi",
  "audio/x-wavpack",
  "video/mp4",
  "video/webm",
  "video/ogg",
  "video/x-msvideo",
  "video/x-flv",
  "video/mpeg",
  "video/3gpp",
  "video/quicktime",
  "video/x-matroska",
  "video/x-theora",
  "application/json",
  "application/xml",
  "application/pdf",
  "application/zip",
  "application/gzip",
  "application/x-bzip2",
  "application/x-7z-compressed",
  "application/x-tar",
  "application/x-rar-compressed",
  "application/x-shockwave-flash",
  "application/x-msdownload",
  "application/x-dosexec",
  "application/x-debian-package",
  "application/x-rpm",
  "application/x-iso9660-image",
  "application/x-img",
  "application/x-httpd-php",
  "application/x-python-code",
  "application/x-java-archive",
  "application/x-sql",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.ms-word",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.oasis.opendocument.text",
  "application/vnd.oasis.opendocument.spreadsheet",
  "application/vnd.oasis.opendocument.presentation",
  "application/vnd.android.package-archive",
  "application/vnd.apple.installer+xml",
  "application/vnd.google-earth.kml+xml",
  "application/vnd.google-earth.kmz",
  "multipart/form-data",
  "multipart/mixed",
  "multipart/related",
  "multipart/alternative",
  "multipart/signed",
  "multipart/encrypted",
  "font/woff",
  "font/woff2",
  "font/ttf",
  "font/otf",
  "font/collection",
  "model/3mf",
  "model/gltf+json",
  "model/gltf-binary",
  "model/obj",
  "model/stl",
  "model/vnd.collada+xml",
  "model/x3d+xml",
  "model/x3d+binary",
  "message/rfc822",
  "message/global",
  "message/disposition-notification",
  "haptics/metadata",
  "haptics/stream",
  "application/vnd.ms-haptics",
  "application/x-nintendo-nes-rom",
  "application/x-snes-rom",
  "application/x-gameboy-rom",
  "application/x-sega-genesis-rom",
  "application/x-playstation-rom",
  "application/x-n64-rom",
  "application/x-dreamcast-rom",
  "application/x-wii-rom",
  "application/x-switch-rom",
]);